config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  resources :products, only: %i(index new create destroy)
  resource :update_cart_sessions, only: :update
  resource :export_pdfs, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  enum tax: {default: 0, free: 1}
  enum type_product: {inland: 0, import: 1}

  validates :name, presence: true, length: {minimum: Settings.name_product.minimum,
    maximum: Settings.name_product.maximum}
  validates :price, presence: true, numericality: {greater_than: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  private

  def set_locale
    I18n.locale = if params[:locale].present?
      params[:locale]
    elsif session[:locale].present?
      session[:locale]
    else
      I18n.default_locale
    end
    session[:locale] = I18n.locale
  end
end

app/controllers/export_pdfs_controller.rb
class ExportPdfsController < ApplicationController
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{t '.export_cart'}_#{Time.current.strftime('%d-%m-%Y')}",
          template: "export_pdfs/show.html.erb",
          disposition: "attachment",
          layout: "export_pdf",
          orientation: "Landscape",
          encoding: "UTF-8"
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: %i(edit update destroy)
  before_action :set_session_cart

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      @products = Product.all
      @success = true
      @message = t ".create_success"
    else
      @success = false
    end
  end

  def destroy
    @product = Product.find_by id: params[:id]
    if @product.destroy
      if session[:cart][@product.id.to_s].present?
        session[:cart].except! @product.id.to_s
      end
      @success = true
      @message = t ".delete_success"
    else
      @success = false
      @message = t ".delete_fail"
    end
  end

  private

  def product_params
    params.require(:product).permit :name, :price, :tax, :type_product

  end

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:alert] = t "product_not_found"
    redirect_to root_path
  end

  def set_session_cart
    session[:cart] = {} unless session[:cart].present?
  end
end

app/controllers/update_cart_sessions_controller.rb
class UpdateCartSessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def update
    if params[:is_delete].present?
      session[:cart].except! params[:product_id].to_s
    else
      product = Product.find_by id: params[:product_id]
      session[:cart][params[:product_id]] = [product, params[:quantity]]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def calculate_tax value
    product = value.first
    price = product["price"].to_f
    tax = product["tax"]
    type = product["type_product"]
    tax_product = 0
    if tax == Settings.tax.default
      tax_product = price * 10 / 100
    end
    if type == Settings.type.import
      tax_product += price * 5 /100
    end
    quantity = value.last.to_f
    (((tax_product * quantity) * 20).ceil / 20.0).round 2
  end

  def calculate_total_price value
    tax = calculate_tax value
    price = value.first["price"].to_f
    quantity = value.last.to_f
    (price * quantity + tax).round 2
  end

  def calculate_tax_all
    tax_all = 0
    session[:cart].each do |key, value|
      tax_all += calculate_tax value
    end
    tax_all.round 2
  end

  def calculate_price_all
    total_price = 0
    session[:cart].each do |key, value|
      total_price += calculate_total_price value
    end
    total_price.round 2
  end
end

app/views/export_pdfs/show.html.erb
<% if session[:cart].present? %>
  <h3 class="text-center uppercase"><%= t "export_pdfs.show.detail_cart" %></h3>
  <h4 class="text-center">
    <%= t "export_pdfs.show.date_export", date: Time.current.strftime("%H:%M:%S %d/%m/%Y") %>
  </h4>
  <table id="export-pdf" class="table table-bordered">
    <thead>
      <tr>
        <td><%= t "export_pdfs.show.stt" %></td>
        <td><%= t "export_pdfs.show.product_name" %></td>
        <td><%= t "export_pdfs.show.unit_price" %></td>
        <td><%= t "export_pdfs.show.quantity" %></td>
        <td><%= t "export_pdfs.show.tax" %></td>
        <td><%= t "export_pdfs.show.type" %></td>
        <td><%= t "export_pdfs.show.tax_sale" %></td>
        <td><%= t "export_pdfs.show.total" %></td>
      </tr>
    </thead>
    <tbody>
      <% session[:cart].each_with_index do |value, index| %>
        <tr>
          <td class="text-center">
            <%= index + 1 %>
          </td>
          <td><%= value.last[0]["name"] %></td>
          <td><%= value.last[0]["price"] %></td>
          <td class="text-center"><%= value.last[1] %></td>
          <td class="text-center">
            <%= value.last[0]["price"] == Settings.tax.default ? "10" : "0" %>
          </td>
          <td class="text-center">
            <%= t "export_pdfs.show.#{value.last[0]['type_product']}" %>
          </td>
          <td class="text-center">$<%= calculate_tax value.last %></td>
          <td class="text-center">$<%= calculate_total_price value.last %></td>
        </tr>
      <% end %>
      <tr>
        <td class="text-center uppercase" colspan="6"><strong><%= t "export_pdfs.show.total" %></strong></td>
        <td class="text-center"><strong>$<%= calculate_tax_all %></strong></td>
        <td class="text-center"><strong>$<%= calculate_price_all %></strong></td>
      </tr>
    </tbody>
  </table>
<% else %>
  <h4 class="text-center"><%= t "export_pdfs.show.cart_not_product" %></h4>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestJobready</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div id="flash-message" class="alert"></div>
    <header>
      <div class="container">
        <%= image_tag "logo", alt: t(".company") %>
        <span class="glyphicon glyphicon-shopping-cart pull-right shopping-cart"></span>
        <div class="change-locale">
          <ul class="list-language">
            <% Settings.languages.each do |key, value| %>
              <li>
                <%= link_to url_for(locale: value.type) do %>
                  <%= image_tag value.image %>
                  <span class="text"><%= value.name %></span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
    <div class="container-shopping-item">
      <div class="shopping-item">
        <% if session[:cart].present? %>
          <% session[:cart].each do |key, value| %>
            <div class="cart-item" data-product-id="<%= key %>"  data-product-tax="<%= value.first["tax"] %>"
               data-product-type="<%= value.first["type_product"] %>">
              <p class="text-right"><span class="remove-cart-item">&times;</span></p>
              <p><strong><%= value.first["name"] %></strong></p>
              <p class="item-price" data-price="<%= value.first["price"] %>">
                $<%= value.first["price"] %>
              </p>
              <span class="glyphicon glyphicon-minus-sign change-quantity
                <%= value.last.to_i > Settings.cart_item.minimum ? '' : 'hide' %>"></span>
              <input type="number" class="quantity text-center" value="<%= value.last %>" step="1" />
              <span class="glyphicon glyphicon-plus-sign change-quantity
                <%= value.last.to_i < Settings.cart_item.maximum ? '' : 'hide' %>"></span>
              <p class="text-right">
                <%= t 'sales_taxes' %>&nbsp;
                $<span class="tax-price"><%= calculate_tax value %></span>
                &ensp;<%= t "total_price" %>&nbsp;
                $<span class="total-price"><%= calculate_total_price value %></span>
              </p>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="total-price-cart-item <%= session[:cart].present? ? '' : 'hide' %>">
        <p class="text-right">
          <strong><%= t "sales_taxes" %></strong>
          &nbsp;$<span class="tax-all"><%= calculate_tax_all %></span>
        </p>
        <p class="text-right">
          <strong><%= t "total_price" %></strong>
          &nbsp;$<span class="total-price-all"><%= calculate_price_all %></span>
        </p>
      </div>
      <h4 class="text-center cart-not-have-product <%= session[:cart].present? ? 'hide' : '' %>">
        <%= t "not_have_product_in_cart" %>
      </h4>
      <div class="export-pdf <%= session[:cart].present? ? '' : 'hide' %>">
        <%= link_to export_pdfs_path(format: Settings.export_type.pdf), target: :_blank do %>
          <span class="glyphicon glyphicon-download"></span>
          <%= t "export_pdf" %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/export_pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= wicked_pdf_stylesheet_link_tag "export_pdf" %>
    <%= csrf_meta_tags %>
    <meta name="turbolinks-cache-control" content="no-cache">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, remote: true do |f| %>
  <div class="form-group">
    <%= f.label :name, t(".name") %>
    <%= f.text_field :name, class: "form-control" %>
    <p class="error-message">
      <%= @product.errors.full_messages_for(:name).first %>
    </p>
  </div>
  <div class="form-group">
    <%= f.label :price, t(".price") %>
    <%= f.number_field :price, class: "form-control" %>
    <p class="error-message">
      <%= @product.errors.full_messages_for(:price).first %>
    </p>
  </div>
  <div class="form-group">
    <%= f.label :tax, t(".tax") %>
    <%= f.select :tax, options_for_select(Product.taxes.map{|key, value| [t(".#{key}"), key]}), {},
      class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :type_product, t(".type_product") %>
    <%= f.select :type_product, options_for_select(Product.type_products.map{|key, value| [t(".#{key}"), key]}), {},
      class: "form-control" %>
  </div>
  <div class="text-center">
    <%= f.submit t("save"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-md-3 col-sm-4 col-xs-6" data-product-id="<%= product.id %>">
  <div class="item relative">
    <p class="product-name">
      <%= product.name %>
      <%= link_to "", product, method: :delete, data: {confirm: t("are_you_sure")}, remote: true,
        class: "glyphicon glyphicon-minus-sign remove-product" %>
    </p>
    <p class="product-price">
      $<%= product.price %>
      <span class="glyphicon glyphicon-shopping-cart pull-right add-shopping-cart
        <%= session[:cart].key?(product.id.to_s) ? 'hide' : '' %>"
        title="<%= t '.add_shopping_cart' %>" data-product-name="<%= product.name %>"
        data-product-price="<%= product.price %>" data-product-tax="<%= product.tax %>"
        data-product-type="<%= product.type_product %>"></span>
    </p>
  </div>
</div>

app/views/products/create.js.erb
<% if @success %>
  $('.container .row').html('<%= j render @products %><div class="col-md-3 col-sm-4 col-xs-6">'
    + '<div class="item add-new-product">'
    + '<%= j link_to t("products.index.add_product"), new_product_path, remote: true %></div></div>');
  $('#my-product').modal('hide');
  $('#flash-message').removeClass('alert-danger').addClass('alert-success')
    .html('<%= @message %>').slideDown().delay(3000).slideUp();
<% else %>
  $('#my-product .modal-body').html('<%= j render "form" %>')
<% end %>

app/views/products/destroy.js.erb
<% if @success %>
  $(document).find('div[data-product-id=<%= @product.id %>]').remove();
  calculateTotalPriceAllProduct();
  $('#flash-message').removeClass('alert-danger').addClass('alert-success')
    .html('<%= @message %>').slideDown().delay(3000).slideUp();
  if ($(document).find('.cart-item').length == 0) {
    $('.cart-not-have-product').removeClass('hide');
    $('.total-price-cart-item').addClass('hide');
    $('div.export-pdf').addClass('hide');
  }
<% else %>
  $('#flash-message').removeClass('alert-success').addClass('alert-danger')
    .html('<%= @message %>').slideDown().delay(3000).slideUp();
<% end %>

function calculateTotalPriceAllProduct() {
  var all_item = $(document).find('.cart-item');
  var tax_all = 0;
  var total_price = 0;
  $.each(all_item, function(index, item) {
    var quantity = parseFloat($(item).find('input.quantity').val());
    var price = parseFloat($(item).find('.item-price').data('price'));
    var tax = $(item).data('product-tax');
    var type = $(item).data('product-type');
    var tax_product = 0;
    if (tax == "default") {
      tax_product = price * 10 / 100;
    }
    if (type == "import") {
      tax_product += price * 5 / 100;
    }
    tax_all += Math.ceil(tax_product * quantity * 20) / 20.0;
    total_price += price * quantity;
  });
  $('.total-price-cart-item .tax-all').html(tax_all.toFixed(2));
  $('.total-price-cart-item .total-price-all').html((total_price + tax_all).toFixed(2));
}

app/views/products/index.html.erb
<div class="row">
  <%= render @products %>
  <div class="col-md-3 col-sm-4 col-xs-6">
    <div class="item add-new-product">
      <%= link_to t(".add_product"), new_product_path, remote: true %>
    </div>
  </div>
</div>
<div id="my-product" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= t ".new_product_title" %></h4>
      </div>
      <div class="modal-body"></div>
    </div>
  </div>
</div>

app/views/products/new.js.erb
$('#my-product .modal-body').html('<%= j render "form" %>')
$('#my-product').modal('show');